from receipt import Receipt
import json

"""
This script contains unit tests that will be run using pytest.
"""


def test_json_date():
    """
    Check if the date in the JSON file generated by create_json_file()
    is equal to the date in the sample JSON file.
    """
    with open("./data/valid_ticket1.json", "r") as f:
        true_data = json.load(f)
    with open("./sample_J122_249302.json", "r") as f:
        my_data = json.load(f)
    assert my_data['date'] == true_data['date']


def test_json_store_address():
    """
    Check if the store address in the JSON file generated by
    create_json_file() is equal to the address in the sample JSON file.
    """
    with open("./data/valid_ticket1.json", "r") as f:
        true_data = json.load(f)
    with open("./sample_J122_249302.json", "r") as f:
        my_data = json.load(f)
    assert my_data['storeAddress'] == true_data['storeAddress']


def test_json_invoice_number():
    """
    Check if the invoice number in the JSON file generated by
    create_json_file() is equal to the invoice number in the sample JSON file.
    """
    with open("./data/valid_ticket1.json", "r") as f:
        true_data = json.load(f)
    with open("./sample_J122_249302.json", "r") as f:
        my_data = json.load(f)
    assert my_data['invoiceNumber'] == true_data['invoiceNumber']


def test_json_subtotal():
    """
    Check if the subtotal in the JSON file generated by create_json_file()
    is equal to the subtotal in the sample JSON file.
    """
    with open("./data/valid_ticket1.json", "r") as f:
        true_data = json.load(f)
    with open("./sample_J122_249302.json", "r") as f:
        my_data = json.load(f)
    assert my_data['subtotal'] == true_data['subtotal']


def test_json_total():
    """
    Check if the total in the JSON file generated by create_json_file()
    is equal to the total in the sample JSON file.
    """
    with open("./data/valid_ticket1.json", "r") as f:
        true_data = json.load(f)
    with open("./sample_J122_249302.json", "r") as f:
        my_data = json.load(f)
    assert my_data['total'] == true_data['total']


def test_json_line_items():
    """
    Check if each line item in the JSON file generated by create_json_file()
    is equal to the corresponding line item in the sample JSON file.
    """
    with open("./data/valid_ticket1.json", "r") as f:
        true_data = json.load(f)
    with open("./sample_J122_249302.json", "r") as f:
        my_data = json.load(f)
    for i in range(len(my_data)):
        assert my_data['lineItems'][i]['sku'] \
            == true_data['lineItems'][i]['sku']
        assert my_data['lineItems'][i]['description'] \
            == true_data['lineItems'][i]['description']
        assert my_data['lineItems'][i]['total'] \
            == true_data['lineItems'][i]['total']
        assert my_data['lineItems'][i]['taxCode'] \
            == true_data['lineItems'][i]['taxCode']
